Feat/melih branch mvp api
Rater-Inc/dotnet-api pull request #43
Opened 2024-07-08 02:36 UTC by Sirmelihy

FIX #34

2024-07-08 17:31 UTC, BharatSoni23 reviewed
Hello,
My name is Bharat. I'm a dot net developer and I have 2 years of experience. I have checked the code and it's a good approach to handle errors.

2024-07-08 17:41 UTC, Sirmelihy commented
> Hello, My name is Bharat. I'm a dot net developer and I have 2 years of experience. I have checked the code and it's a good approach to handle errors.

Hi Bharat,

Thank you for your contribution. May I kindly ask how you discovered our project?

Wishing you the best of luck.

2024-07-08 17:57 UTC, BharatSoni23 commented
> > Hello, My name is Bharat. I'm a dot net developer and I have 2 years of experience. I have checked the code and it's a good approach to handle errors.
> 
> Hi Bharat,
> 
> Thank you for your contribution. May I kindly ask how you discovered our project?
> 
> Wishing you the best of luck.

Hello @Sirmelihy,
I have searched for a project for contribution and I found your project at the top of my search.
Can you please guide me on how I can contribute to open-source projects?

Thank you

2024-07-08 21:29 UTC, fehmisener commented
> > > Hello, My name is Bharat. I'm a dot net developer and I have 2 years of experience. I have checked the code and it's a good approach to handle errors.
> > 
> > 
> > Hi Bharat,
> > Thank you for your contribution. May I kindly ask how you discovered our project?
> > Wishing you the best of luck.
> 
> Hello @Sirmelihy, I have searched for a project for contribution and I found your project at the top of my search. Can you please guide me on how I can contribute to open-source projects?
> 
> Thank you

Hi Mate,

Of course you're welcome to contribute our project but it's still in development phase and we usually discuss internally next features and steps. You can watch the repository for the upcoming issues (or you can raise an one) and taking the responsibility of it. Then, all you need to do is following branch creation and clean-code rules.

2024-07-08 22:29 UTC, fehmisener requested changes
Check my comments and we are sure that it handles all possible exceptions

2024-07-08 22:29 UTC, fehmisener commented on Rater.Business/Configurations/GlobalExceptionHandlingMiddleware.cs
> +            string message = "";
Why this is `""`and other one is string.Empty

2024-07-08 22:29 UTC, fehmisener commented on Rater.Business/Configurations/GlobalExceptionHandlingMiddleware.cs
> +            if(exceptionType == typeof(UnauthorizedAccessException))
Do you really need this if structure? Why you don't set `ex.Message`, `ex.StackTrace ?? string.Empty` and `success` above just once. And I feel like this status code extraction should be a new method. Check this implementation:

```csharp
public async Task HandleExceptionAsync(HttpContext context, Exception ex)
{
    var exceptionType = ex.GetType();
    var (success, status) = GetExceptionDetails(exceptionType);
    
    var message = ex.Message;
    var stackTrace = ex.StackTrace ?? string.Empty;

    _logger.LogError(ex, "An error occurred: {Message}, StackTrace: {StackTrace}", message, stackTrace);

    var exceptionResult = JsonSerializer.Serialize(new { success, status, message, stackTrace });
    
    context.Response.ContentType = "application/json";
    context.Response.StatusCode = (int)status;
    await context.Response.WriteAsync(exceptionResult);
}

private static (bool success, HttpStatusCode status) GetExceptionDetails(Type exceptionType)
{
    return exceptionType switch
    {
        Type t when t == typeof(UnauthorizedAccessException) => (false, HttpStatusCode.Unauthorized),
        Type t when t == typeof(InvalidOperationException) => (false, HttpStatusCode.BadRequest),
        Type t when t == typeof(ArgumentException) => (false, HttpStatusCode.BadRequest),
        _ => (false, HttpStatusCode.InternalServerError)
    };
}
```

2024-07-09 15:37 UTC, BharatSoni23 commented
> > > > Hello, My name is Bharat. I'm a dot net developer and I have 2 years of experience. I have checked the code and it's a good approach to handle errors.
> > > 
> > > 
> > > Hi Bharat,
> > > Thank you for your contribution. May I kindly ask how you discovered our project?
> > > Wishing you the best of luck.
> > 
> > 
> > Hello @Sirmelihy, I have searched for a project for contribution and I found your project at the top of my search. Can you please guide me on how I can contribute to open-source projects?
> > Thank you
> 
> Hi mate,
> 
> Of course you're welcome to contribute our project but it's still in development phase and we usually discuss internally next features and steps. You can watch the repository for the upcoming issues (or you can raise an one) and taking the responsibility of it. Then, all you need to do is following branch creation and clean-code rules.

Hi @fehmisener 
Thank you for including me to contribute in your project. I have checked your project code and many classes are has unwanted using like 'using System.text' so it will be a great approach to delete them. Can I do this?

2024-07-09 15:56 UTC, fehmisener approved these changes

2024-07-09 20:48 UTC, Sirmelihy commented
> > > > > Hello, My name is Bharat. I'm a dot net developer and I have 2 years of experience. I have checked the code and it's a good approach to handle errors.
> > > > 
> > > > 
> > > > Hi Bharat,
> > > > Thank you for your contribution. May I kindly ask how you discovered our project?
> > > > Wishing you the best of luck.
> > > 
> > > 
> > > Hello @Sirmelihy, I have searched for a project for contribution and I found your project at the top of my search. Can you please guide me on how I can contribute to open-source projects?
> > > Thank you
> > 
> > 
> > Hi mate,
> > Of course you're welcome to contribute our project but it's still in development phase and we usually discuss internally next features and steps. You can watch the repository for the upcoming issues (or you can raise an one) and taking the responsibility of it. Then, all you need to do is following branch creation and clean-code rules.
> 
> Hi @fehmisener Thank you for including me to contribute in your project. I have checked your project code and many classes are has unwanted using like 'using System.text' so it will be a great approach to delete them. Can I do this?

Check the issues. I created one , you are welcome to work on it.

2024-07-09 20:49 UTC, merged